% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={11: Crafting Reports},
  pdfauthor={Nancy Bao},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin= 2.54cm]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{11: Crafting Reports}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Environmental Data Analytics \textbar{} John Fay \& Luana Lima
\textbar{} Developed by Kateri Salk}
\author{Nancy Bao}
\date{Spring 2021}

\begin{document}
\maketitle

\hypertarget{lesson-objectives}{%
\subsection{LESSON OBJECTIVES}\label{lesson-objectives}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Describe the purpose of using R Markdown as a communication and
  workflow tool
\item
  Incorporate Markdown syntax into documents
\item
  Communicate the process and findings of an analysis session in the
  style of a report
\end{enumerate}

\hypertarget{use-of-r-studio-r-markdown-so-far}{%
\subsection{USE OF R STUDIO \& R MARKDOWN SO
FAR\ldots{}}\label{use-of-r-studio-r-markdown-so-far}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Write code
\item
  Document that code
\item
  Generate PDFs of code and its outputs
\item
  Integrate with Git/GitHub for version control
\end{enumerate}

\hypertarget{basic-r-markdown-document-structure}{%
\subsection{BASIC R MARKDOWN DOCUMENT
STRUCTURE}\label{basic-r-markdown-document-structure}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{YAML Header} surrounded by --- on top and bottom

  \begin{itemize}
  \tightlist
  \item
    YAML templates include options for html, pdf, word, markdown, and
    interactive
  \item
    More information on formatting the YAML header can be found in the
    cheat sheet
  \end{itemize}
\item
  \textbf{R Code Chunks} surrounded by
  ``\texttt{on\ top\ and\ bottom\ \ \ \ \ +\ Create\ using}Cmd/Ctrl\texttt{+}Alt\texttt{+}I`

  \begin{itemize}
  \tightlist
  \item
    Can be named \{r name\} to facilitate navigation and autoreferencing
  \item
    Chunk options allow for flexibility when the code runs and when the
    document is knitted
  \end{itemize}
\item
  \textbf{Text} with formatting options for readability in knitted
  document
\end{enumerate}

\hypertarget{resources}{%
\subsection{RESOURCES}\label{resources}}

Handy cheat sheets for R markdown can be found:
\href{https://rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf}{here},
and
\href{https://raw.githubusercontent.com/rstudio/cheatsheets/master/rmarkdown-2.0.pdf}{here}.

There's also a quick reference available via the
\texttt{Help}→\texttt{Markdown\ Quick\ Reference} menu.

Lastly, this \href{https://rmarkdown.rstudio.com}{website} give a great
\& thorough overview.

\hypertarget{the-knitting-process}{%
\subsection{THE KNITTING PROCESS}\label{the-knitting-process}}

\includegraphics{../lessons/img/rmarkdownflow.png} - The knitting
sequence

\begin{itemize}
\tightlist
\item
  Knitting commands in code chunks:
\item
  \texttt{include\ =\ FALSE} - code is run, but neither code nor results
  appear in knitted file
\item
  \texttt{echo\ =\ FALSE} - code not included in knitted file, but
  results are
\item
  \texttt{eval\ =\ FALSE} - code is not run in the knitted file
\item
  \texttt{message\ =\ FALSE} - messages do not appear in knitted file
\item
  \texttt{warning\ =\ FALSE} - warnings do not appear\ldots{}
\item
  \texttt{fig.cap\ =\ "..."} - adds a caption to graphical results
\end{itemize}

\hypertarget{what-else-can-r-markdown-do}{%
\subsection{WHAT ELSE CAN R MARKDOWN
DO?}\label{what-else-can-r-markdown-do}}

See: \url{https://rmarkdown.rstudio.com} and class recording. *
Languages other than R\ldots{} * Various outputs\ldots{}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{why-r-markdown}{%
\subsection{WHY R MARKDOWN?}\label{why-r-markdown}}

\textless Fill in our discussion below with bullet points. Use italics
and bold for emphasis (hint: use the cheat sheets or \texttt{Help}
→\texttt{Markdown\ Quick\ Reference} to figure out how to make bold and
italic text).\textgreater{}

\begin{itemize}
\tightlist
\item
  \textbf{\emph{concise in keeping code and report together}}
\item
  \textbf{\emph{easy for creating data visualization}}
\item
  \textbf{\emph{generates professional deliverable}}
\end{itemize}

\hypertarget{text-editing-challenge}{%
\subsection{TEXT EDITING CHALLENGE}\label{text-editing-challenge}}

Create a table below that details the example datasets we have been
using in class. The first column should contain the names of the
datasets and the second column should include some relevant information
about the datasets. (Hint: use the cheat sheets to figure out how to
make a table in Rmd)

\hypertarget{table-1.-data-set-descriptions}{%
\subsubsection{Table 1. Data set
Descriptions}\label{table-1.-data-set-descriptions}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.36}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.64}}@{}}
\toprule
Data Set & Description of data set \\
\midrule
\endhead
CDC Social Vulnerability Index & 2018 North Carolina county level data
collected from \\
& the CDC Agency for Toxic Substances and Disease \\
& Registry \\
------------------------------- &
------------------------------------------------------ \\
ECOTOX Neonicotinoids & Neonicotinoids and insect effects data
collected \\
& from the US EPA ECOTOX Knowledgebase \\
------------------------------- &
------------------------------------------------------ \\
EPA Air Quality & Air quality data from EPA monitoring sites in North \\
& Carolina measuring PM2.5 and ozone from 2017 to 2018 \\
------------------------------- &
------------------------------------------------------ \\
NEON Niwot Ridge litter & Small woody debris and litter data collected
from \\
& 2016 to 2019 at the Niwot Ridge Long-Term Ecological \\
& Research (LTER) station \\
------------------------------- &
------------------------------------------------------ \\
NTL-LTER Lake Datasets & Data collected from lakes in the North
Temperate \\
& Lakes District in Wisconsin, USA from 1984 to 2016 \\
------------------------------- &
------------------------------------------------------ \\
USGS Streamflow data for site & Streamflow data from the Eno River, NC
streamflow \\
02085000 & gage site 02085000 in North Carolina collected from \\
& 1928-01-01 and 2019-12-26. \\
\bottomrule
\end{longtable}

\hypertarget{r-chunk-editing-challenge}{%
\subsection{R CHUNK EDITING CHALLENGE}\label{r-chunk-editing-challenge}}

\hypertarget{installing-packages}{%
\subsubsection{Installing packages}\label{installing-packages}}

Create an R chunk below that installs the package \texttt{knitr}.
Instead of commenting out the code, customize the chunk options such
that the code is not evaluated (i.e., not run).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"knitr"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{setup}{%
\subsubsection{Setup}\label{setup}}

Create an R chunk below called ``setup'' that checks your working
directory, loads the packages \texttt{tidyverse}, \texttt{lubridate},
and \texttt{knitr}, and sets a ggplot theme. Remember that you need to
disable R throwing a message, which contains a check mark that cannot be
knitted.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Check working directory}
\FunctionTok{getwd}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "/Users/Nancy/Desktop/Semester 4/ENV 872L/Environmental_Data_Analytics_2021"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Load libraries}
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(lubridate)}
\FunctionTok{library}\NormalTok{(knitr)}
\FunctionTok{library}\NormalTok{(RColorBrewer) }\CommentTok{\#loaded for more color palettes for the plots{-}used Dark2 palette}
\FunctionTok{library}\NormalTok{(kableExtra)}
\CommentTok{\#I used the URL below to read about kableExtra for:}
\CommentTok{\#formatting my tables for the Data Exploration, Wrangling, Visualization section}
\CommentTok{\#https://cran.r{-}project.org/web/packages/kableExtra/vignettes/awesome\_table\_in\_html.html}
\CommentTok{\#Set a ggplot theme }
\NormalTok{A11\_theme }\OtherTok{\textless{}{-}}\FunctionTok{theme\_bw}\NormalTok{(}\AttributeTok{base\_size=}\DecValTok{14}\NormalTok{)}\SpecialCharTok{+}
            \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"top"}\NormalTok{, }
            \AttributeTok{legend.justification =} \StringTok{"center"}\NormalTok{,}
            \AttributeTok{legend.text =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{14}\NormalTok{,}\AttributeTok{color =} \StringTok{"black"}\NormalTok{),}
            \AttributeTok{legend.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{14}\NormalTok{,}\AttributeTok{color =} \StringTok{"black"}\NormalTok{,}
                                        \AttributeTok{face=} \StringTok{"bold"}\NormalTok{),}
            \AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{,}\AttributeTok{size=}\DecValTok{14}\NormalTok{))}
\FunctionTok{theme\_set}\NormalTok{(A11\_theme)}
\end{Highlighting}
\end{Shaded}

Load the NTL-LTER\_Lake\_Nutrients\_Raw dataset, display the head of the
dataset, and set the date column to a date format.

Customize the chunk options such that the code is run but is not
displayed in the final document.

\hypertarget{data-exploration-wrangling-and-visualization}{%
\subsubsection{Data Exploration, Wrangling, and
Visualization}\label{data-exploration-wrangling-and-visualization}}

Create an R chunk below to create a processed dataset do the following
operations:

\begin{itemize}
\tightlist
\item
  Include all columns except lakeid, depth\_id, and comments
\item
  Include only surface samples (depth = 0 m)
\item
  Drop rows with missing data
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Create processed dataset for NTL{-}LTER\_Lake\_Nutrients\_Raw dataset}
\NormalTok{NTL\_nutrients\_processed }\OtherTok{\textless{}{-}}\NormalTok{ NTL\_nutrients }\SpecialCharTok{\%\textgreater{}\%}
                            \FunctionTok{select}\NormalTok{(lakename}\SpecialCharTok{:}\NormalTok{sampledate,depth}\SpecialCharTok{:}\NormalTok{po4) }\SpecialCharTok{\%\textgreater{}\%}
                            \FunctionTok{filter}\NormalTok{(depth }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
                            \FunctionTok{drop\_na}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

Create a second R chunk to create a summary dataset with the mean,
minimum, maximum, and standard deviation of total nitrogen
concentrations for each lake. Create a second summary dataset that is
identical except that it evaluates total phosphorus. Customize the chunk
options such that the code is run but not displayed in the final
document.

Create a third R chunk that uses the function \texttt{kable} in the
knitr package to display two tables: one for the summary dataframe for
total N and one for the summary dataframe of total P. Use the
\texttt{caption\ =\ "\ "} code within that function to title your
tables. Customize the chunk options such that the final table is
displayed but not the code used to generate the table.

\begin{table}[!h]

\caption{\label{tab:NandP.tbls}Descriptive Statistics for Total Nitrogen Concentrations in the Lakes at the North Temperate Lakes Long Term Ecological Research Site}
\centering
\begin{tabular}[t]{lrrrr}
\toprule
Lake name & Mean (ug/L) & Standard Deviation (ug/L) & Minimum (ug/L) & Maximum (ug/L)\\
\midrule
Central Long Lake & 690.0469 & 209.09341 & 343.020 & 953.063\\
Crampton Lake & 362.6813 & 12.05748 & 353.380 & 376.304\\
East Long Lake & 810.7834 & 335.41457 & 380.620 & 2608.956\\
Hummingbird Lake & 1036.6695 & 204.36889 & 779.053 & 1221.960\\
Paul Lake & 368.7564 & 106.34741 & 45.670 & 628.625\\
\addlinespace
Peter Lake & 561.8752 & 305.64909 & 219.720 & 2048.151\\
Tuesday Lake & 423.5605 & 78.84522 & 237.363 & 554.418\\
West Long Lake & 762.6017 & 402.95992 & 303.170 & 2870.302\\
\bottomrule
\end{tabular}
\end{table}

\begin{table}[!h]

\caption{\label{tab:NandP.tbls}Descriptive Statistics for Total Phosphorus Concentrations in the Lakes at the North Temperate Lakes Long Term Ecological Research Site}
\centering
\begin{tabular}[t]{lrrrr}
\toprule
Lake name & Mean (ug/L) & Standard Deviation (ug/L) & Minimum (ug/L) & Maximum (ug/L)\\
\midrule
Central Long Lake & 21.70981 & 7.076388 & 8.190 & 37.270\\
Crampton Lake & 11.16033 & 4.946759 & 5.803 & 15.555\\
East Long Lake & 29.28984 & 17.375710 & 8.000 & 101.050\\
Hummingbird Lake & 36.21925 & 4.146717 & 32.765 & 42.119\\
Paul Lake & 10.45606 & 4.805142 & 1.222 & 36.070\\
\addlinespace
Peter Lake & 18.39153 & 10.976205 & 0.000 & 64.383\\
Tuesday Lake & 11.71853 & 3.044289 & 6.325 & 18.663\\
West Long Lake & 19.82981 & 10.541276 & 2.690 & 63.243\\
\bottomrule
\end{tabular}
\end{table}

Create a fourth and fifth R chunk that generates two plots (one in each
chunk): one for total N over time with different colors for each lake,
and one with the same setup but for total P. Decide which geom option
will be appropriate for your purpose, and select a color palette that is
visually pleasing and accessible. Customize the chunk options such that
the final figures are displayed but not the code used to generate the
figures. In addition, customize the chunk options such that the figures
are aligned on the left side of the page. Lastly, add a fig.cap chunk
option to add a caption (title) to your plot that will display
underneath the figure.

\begin{figure}[H]

\includegraphics{11_CraftingReports_files/figure-latex/totalN.plot-1} \hfill{}

\caption{Total nitrogen surface (depth=0m) concentrations in lakes at the North Temperate Lakes Long Term Ecological Research Site}\label{fig:totalN.plot}
\end{figure}

\begin{figure}[H]

\includegraphics{11_CraftingReports_files/figure-latex/totalP.plot-1} \hfill{}

\caption{Total phosphorus surface (depth=0m) concentrations in lakes at the North Temperate Lakes Long Term Ecological Research Site}\label{fig:totalP.plot}
\end{figure}

\hypertarget{communicating-results}{%
\subsubsection{Communicating results}\label{communicating-results}}

Write a paragraph describing your findings from the R coding challenge
above. This should be geared toward an educated audience but one that is
not necessarily familiar with the dataset. Then insert a horizontal rule
below the paragraph. Below the horizontal rule, write another paragraph
describing the next steps you might take in analyzing this dataset. What
questions might you be able to answer, and what analyses would you
conduct to answer those questions?

\begin{quote}
As shown in Figure 1 and 2 respectively, total nitrogen and total
phosphorus concentrations were measured and collected across eight lakes
from the North Temperate Lakes Long Term Ecological Research Site in
Wisconsin, USA from May 1991 to August 1999. The following lakes were
measured for their total nitrogen and total phosphorus nutrient
concentrations in micrograms per liter: Central Long Lake, Crampton
Lake, East Long Lake, Hummingbird Lake, Paul Lake, Peter Lake, Tuesday
Lake, and West Long Lake.These nutrient concentrations (ug/L) are
measured from the surface depth of each lake (depth=0m). In figure 1,
the total nitrogen concentrations follow a seasonal pattern where
concentrations peak during the late spring to mid-summer months and
decrease during the late fall to winter months. In figure 2, the total
phosphorus concentrations also a follow a seasonal pattern, where
phosphorus concentrations peak in the summer to fall months. Of the
eight lakes,total phosphorus and total nitrogen concentration
measurements for East Long Lake across 1991 to 1999 are greater than
that of the other lakes (Figs. 1 and 2). The nutrient concentrations for
Peter Lake and Tuesday Lake do not greatly fluctuate from 1991 to 1999,
but nutrient concentrations increased from May 1996 to March 1997 and
decreased from May 1997 to August 1998 for East Long Lake, Peter Lake,
and West Long Lake (Figs. 1 and 2). For the overall averages for total
nitrogen concentration, Hummingbird Lake had the highest value at 1037
ug/L (Table 2) and for the overall averages for total phosphorus
concentration, Hummingbird Lake had the highest value at 36.2 ug/L
(Table 3).
\end{quote}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{quote}
This dataset can be used to assess the impacts of nutrient pollution
from upstream nonpoint runoff sources such as agricultural fertilizer
and pesticide runoff surrounding Wisconsin from 1991 to 1999. The
dataset can be used to explore research questions such as: ``How the
total phosphorus and nitrogen concentrations vary within a lake and
between other lakes?'' and ``What factors change nitrogen and phosphorus
concentrations in these lakes?'' To elucidate the legacy effects of the
nutrient effluent time series analyses can be conducted on each lake to
assess trends across 1991 and 1999 and multiple linear regression
analyses can be conducted to assess factors that are associated with
total nitrogen and phosphorus lake concentrations. Furthermore, nitrogen
nutrient concentrations can be further divided into the concentrations
of nitrate versus ammonium to compare distribution of nitrogen forms in
each lake. Others may be interested in looking at nutrient
concentrations across varying depths in each of the lakes, in which
including additional data such as water depths and other aspects such as
seasonality may be included for further analyses on the effects of
nutrient pollution within a lake and across different lakes.
\end{quote}

\hypertarget{knit-your-pdf}{%
\subsection{KNIT YOUR PDF}\label{knit-your-pdf}}

When you have completed the above steps, try knitting your PDF to see if
all of the formatting options you specified turned out as planned. This
may take some troubleshooting.

\hypertarget{other-r-markdown-customization-options}{%
\subsection{OTHER R MARKDOWN CUSTOMIZATION
OPTIONS}\label{other-r-markdown-customization-options}}

We have covered the basics in class today, but R Markdown offers many
customization options. A word of caution: customizing templates will
often require more interaction with LaTeX and installations on your
computer, so be ready to troubleshoot issues.

Customization options for pdf output include: * Table of contents *
Number sections * Control default size of figures * Citations * Template
(more info
\href{http://jianghao.wang/post/2017-12-08-rmarkdown-templates/}{here})

pdf\_document:\\
toc: true\\
number\_sections: true\\
fig\_height: 3\\
fig\_width: 4\\
citation\_package: natbib\\
template:

\end{document}
