% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Assignment 7: Time Series Analysis},
  pdfauthor={Nancy Bao},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=2.54cm]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Assignment 7: Time Series Analysis}
\author{Nancy Bao}
\date{}

\begin{document}
\maketitle

\hypertarget{overview}{%
\subsection{OVERVIEW}\label{overview}}

This exercise accompanies the lessons in Environmental Data Analytics on
time series analysis.

\hypertarget{directions}{%
\subsection{Directions}\label{directions}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Change ``Student Name'' on line 3 (above) with your name.
\item
  Work through the steps, \textbf{creating code and output} that fulfill
  each instruction.
\item
  Be sure to \textbf{answer the questions} in this assignment document.
\item
  When you have completed the assignment, \textbf{Knit} the text and
  code into a single PDF file.
\item
  After Knitting, submit the completed exercise (PDF file) to the
  dropbox in Sakai. Add your last name into the file name (e.g.,
  ``Fay\_A07\_TimeSeries.Rmd'') prior to submission.
\end{enumerate}

The completed exercise is due on Tuesday, March 16 at 11:59 pm.

\hypertarget{set-up}{%
\subsection{Set up}\label{set-up}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Set up your session:
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Check your working directory
\item
  Load the tidyverse, lubridate, zoo, and trend packages
\item
  Set your ggplot theme
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Import the ten datasets from the Ozone\_TimeSeries folder in the Raw
  data folder. These contain ozone concentrations at Garinger High
  School in North Carolina from 2010-2019 (the EPA air database only
  allows downloads for one year at a time). Import these either
  individually or in bulk and then combine them into a single dataframe
  named \texttt{GaringerOzone} of 3589 observation and 20 variables.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#1}
\CommentTok{\#Check working directory}
\FunctionTok{getwd}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "/Users/Nancy/Desktop/Semester 4/ENV 872L/Environmental_Data_Analytics_2021"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Load packages}
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(plyr)}
\FunctionTok{library}\NormalTok{(lubridate)}
\FunctionTok{library}\NormalTok{(zoo)}
\FunctionTok{library}\NormalTok{(trend)}
\CommentTok{\#Set ggplot theme}
\NormalTok{theme07}\OtherTok{\textless{}{-}}\FunctionTok{theme\_bw}\NormalTok{(}\AttributeTok{base\_size=}\DecValTok{12}\NormalTok{)}\SpecialCharTok{+}
           \FunctionTok{theme}\NormalTok{(}\AttributeTok{plot.title=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size=}\DecValTok{12}\NormalTok{, }
                                    \AttributeTok{face=}\StringTok{"bold"}\NormalTok{, }
                                    \AttributeTok{color=}\StringTok{"black"}\NormalTok{,}
                                    \AttributeTok{hjust=}\FloatTok{0.5}\NormalTok{),}
                 \AttributeTok{axis.text =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{color =} \StringTok{"black"}\NormalTok{),}
                 \AttributeTok{axis.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{color=} \StringTok{"black"}\NormalTok{,}\AttributeTok{face=} \StringTok{"bold"}\NormalTok{),}
                 \AttributeTok{legend.position =} \StringTok{"top"}\NormalTok{)}
\FunctionTok{theme\_set}\NormalTok{(theme07)}

\CommentTok{\#2 Import Ozone\_TimeSeries data using list.files }
\NormalTok{Ozone\_Garinger\_files }\OtherTok{=} \FunctionTok{list.files}\NormalTok{(}\AttributeTok{path =} \StringTok{"./Data/Raw/Ozone\_TimeSeries/"}\NormalTok{, }
                                  \AttributeTok{pattern=}\StringTok{"*.csv"}\NormalTok{, }\AttributeTok{full.names=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{Ozone\_Garinger\_files}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "./Data/Raw/Ozone_TimeSeries//EPAair_O3_GaringerNC2010_raw.csv"
##  [2] "./Data/Raw/Ozone_TimeSeries//EPAair_O3_GaringerNC2011_raw.csv"
##  [3] "./Data/Raw/Ozone_TimeSeries//EPAair_O3_GaringerNC2012_raw.csv"
##  [4] "./Data/Raw/Ozone_TimeSeries//EPAair_O3_GaringerNC2013_raw.csv"
##  [5] "./Data/Raw/Ozone_TimeSeries//EPAair_O3_GaringerNC2014_raw.csv"
##  [6] "./Data/Raw/Ozone_TimeSeries//EPAair_O3_GaringerNC2015_raw.csv"
##  [7] "./Data/Raw/Ozone_TimeSeries//EPAair_O3_GaringerNC2016_raw.csv"
##  [8] "./Data/Raw/Ozone_TimeSeries//EPAair_O3_GaringerNC2017_raw.csv"
##  [9] "./Data/Raw/Ozone_TimeSeries//EPAair_O3_GaringerNC2018_raw.csv"
## [10] "./Data/Raw/Ozone_TimeSeries//EPAair_O3_GaringerNC2019_raw.csv"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#created dataframe from ldply() function in plyr package}
\NormalTok{GaringerOzone }\OtherTok{\textless{}{-}}\NormalTok{ Ozone\_Garinger\_files }\SpecialCharTok{\%\textgreater{}\%}
                 \FunctionTok{ldply}\NormalTok{(read.csv)}
\end{Highlighting}
\end{Shaded}

\hypertarget{wrangle}{%
\subsection{Wrangle}\label{wrangle}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\item
  Set your date column as a date class.
\item
  Wrangle your dataset so that it only contains the columns Date,
  Daily.Max.8.hour.Ozone.Concentration, and DAILY\_AQI\_VALUE.
\item
  Notice there are a few days in each year that are missing ozone
  concentrations. We want to generate a daily dataset, so we will need
  to fill in any missing days with NA. Create a new data frame that
  contains a sequence of dates from 2010-01-01 to 2019-12-31 (hint:
  \texttt{as.data.frame(seq())}). Call this new data frame Days. Rename
  the column name in Days to ``Date''.
\item
  Use a \texttt{left\_join} to combine the data frames. Specify the
  correct order of data frames within this function so that the final
  dimensions are 3652 rows and 3 columns. Call your combined data frame
  GaringerOzone.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 3 Set date column as date class}
\NormalTok{GaringerOzone}\SpecialCharTok{$}\NormalTok{Date}\OtherTok{\textless{}{-}}\FunctionTok{as.Date}\NormalTok{(GaringerOzone}\SpecialCharTok{$}\NormalTok{Date, }\AttributeTok{format =} \StringTok{"\%m/\%d/\%Y"}\NormalTok{)}
\FunctionTok{class}\NormalTok{(GaringerOzone}\SpecialCharTok{$}\NormalTok{Date) }\CommentTok{\#checking class is date}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Date"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 4 Wrangled GaringerOzone to 3 columns and renamed new dataframe:GaringerOzone\_filtered}
\NormalTok{GaringerOzone\_filtered}\OtherTok{\textless{}{-}}\NormalTok{GaringerOzone }\SpecialCharTok{\%\textgreater{}\%}
                        \FunctionTok{select}\NormalTok{(Date, Daily.Max.}\FloatTok{8.}\NormalTok{hour.Ozone.Concentration,}
\NormalTok{                               DAILY\_AQI\_VALUE)}
\CommentTok{\# 5 Created dataframe named Days using seq() and lubridate function ymd()}
\NormalTok{Days}\OtherTok{\textless{}{-}}\FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{seq}\NormalTok{(}\FunctionTok{ymd}\NormalTok{(}\StringTok{"2010{-}01{-}01"}\NormalTok{), }\FunctionTok{ymd}\NormalTok{(}\StringTok{"2019{-}12{-}31"}\NormalTok{),}\AttributeTok{by=}\StringTok{"days"}\NormalTok{))}
\CommentTok{\#rename column name to Date }
\NormalTok{Days}\OtherTok{\textless{}{-}}\FunctionTok{setNames}\NormalTok{(Days,}\FunctionTok{c}\NormalTok{(}\StringTok{"Date"}\NormalTok{))}
\CommentTok{\# 6 used left\_join to combine Days df with the GaringerOzone\_filtered df}
\NormalTok{GaringerOzone}\OtherTok{\textless{}{-}}\FunctionTok{left\_join}\NormalTok{(Days,GaringerOzone\_filtered)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Joining, by = "Date"
\end{verbatim}

\hypertarget{visualize}{%
\subsection{Visualize}\label{visualize}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\tightlist
\item
  Create a line plot depicting ozone concentrations over time. In this
  case, we will plot actual concentrations in ppm, not AQI values.
  Format your axes accordingly. Add a smoothed line showing any linear
  trend of your data. Does your plot suggest a trend in ozone
  concentration over time?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#7 \#created a line plot and rescaled x axis based on 3{-}letter month and Year }
\NormalTok{GaringerOzone\_lineplot}\OtherTok{\textless{}{-}}\FunctionTok{ggplot}\NormalTok{(GaringerOzone,}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Date, }
                                  \AttributeTok{y =}\NormalTok{ Daily.Max.}\FloatTok{8.}\NormalTok{hour.Ozone.Concentration))}\SpecialCharTok{+}
                        \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{+}
                        \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method=}\NormalTok{lm,}\AttributeTok{se=}\ConstantTok{FALSE}\NormalTok{)}\SpecialCharTok{+}
                        \FunctionTok{labs}\NormalTok{(}\AttributeTok{y=}\StringTok{"Daily Maximum 8{-}hr Average Ozone Concentration (ppm)"}\NormalTok{,}
                             \AttributeTok{title=}\StringTok{"Daily Maximum 8{-}hr Average Ozone Concentrations from 2010 to 2019 at Garinger High School in North Carolina"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{scale\_x\_date}\NormalTok{(}\AttributeTok{date\_breaks =} \StringTok{"6 months"}\NormalTok{,}\AttributeTok{date\_labels =} \StringTok{"\%b \%Y"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{90}\NormalTok{, }\AttributeTok{hjust=}\DecValTok{1}\NormalTok{))}
\FunctionTok{print}\NormalTok{(GaringerOzone\_lineplot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{A07_TimeSeries_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{quote}
Answer: The plot suggests that there is a slightly downward trend in
daily maximum 8-hr average ozone concentration from 2010 to 2019,
suggesting the ozone concentration decreases from 2010 to 2019.
\end{quote}

\hypertarget{time-series-analysis}{%
\subsection{Time Series Analysis}\label{time-series-analysis}}

Study question: Have ozone concentrations changed over the 2010s at this
station?

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  Use a linear interpolation to fill in missing daily data for ozone
  concentration. Why didn't we use a piece-wise constant or spline
  interpolation?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#8 Linear interpolation }
\NormalTok{GaringerOzone\_cleaned }\OtherTok{\textless{}{-}} 
\NormalTok{  GaringerOzone }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{( }\AttributeTok{Daily.Max.8hr.Ozone.Conc.Clean=}
\NormalTok{          zoo}\SpecialCharTok{::}\FunctionTok{na.approx}\NormalTok{(Daily.Max.}\FloatTok{8.}\NormalTok{hour.Ozone.Concentration) )}
\CommentTok{\#Daily.Max.8hr.Ozone.Conc.Clean variable is linear interpolation}
\FunctionTok{summary}\NormalTok{(GaringerOzone\_cleaned}\SpecialCharTok{$}\NormalTok{Daily.Max}\FloatTok{.8}\NormalTok{hr.Ozone.Conc.Clean)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 0.00200 0.03200 0.04100 0.04151 0.05100 0.09300
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Graphing the linear interpolation}
\NormalTok{Garinger\_linear\_interpolation}\OtherTok{\textless{}{-}}\FunctionTok{ggplot}\NormalTok{(GaringerOzone\_cleaned) }\SpecialCharTok{+}
                                      \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Date, }
                                      \AttributeTok{y =}\NormalTok{ Daily.Max}\FloatTok{.8}\NormalTok{hr.Ozone.Conc.Clean), }
                                      \AttributeTok{color =} \StringTok{"purple"}\NormalTok{, }\AttributeTok{alpha=}\DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
                                      \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Date, }
                                      \AttributeTok{y =}\NormalTok{ Daily.Max.}\FloatTok{8.}\NormalTok{hour.Ozone.Concentration),}
                                      \AttributeTok{color =} \StringTok{"green"}\NormalTok{,}\AttributeTok{alpha=}\DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
                    \FunctionTok{ylab}\NormalTok{(}\StringTok{"Daily Max. 8{-}hr Average Ozone Concentration (ppm)"}\NormalTok{)}
\FunctionTok{print}\NormalTok{(Garinger\_linear\_interpolation)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A07_TimeSeries_files/figure-latex/unnamed-chunk-4-1.pdf}

\begin{quote}
Answer: We didn't use a spline interpolation because the data does not
follow a quadratic trend. Since the spline interpolation uses a
quadratic function to fill in the missing values, that could potentially
overestimate the missing daily ozone concentrations, since quadratic
functions are based on a polynomial order of 2. We didn't use a
piecewise constant interpolation because our data because we are trying
to see how ozone concentrations change over a continuous time period
from 2010 to 2019 and piecewise constant could use values from an
earlier day or later day that may underestimate or overestimate the
interpolation. You do not know if that nearest neighbor was potentially
an outlier measurement (e.g.~super cloudy or rainy day could alter daily
measurements) that could dramatically change the trend of the data.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\tightlist
\item
  Create a new data frame called \texttt{GaringerOzone.monthly} that
  contains aggregated data: mean ozone concentrations for each month. In
  your pipe, you will need to first add columns for year and month to
  form the groupings. In a separate line of code, create a new Date
  column with each month-year combination being set as the first day of
  the month (this is for graphing purposes only)
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#9}
\NormalTok{GaringerOzone.monthly}\OtherTok{\textless{}{-}}\NormalTok{GaringerOzone\_cleaned }\SpecialCharTok{\%\textgreater{}\%}
                       \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Month =} \FunctionTok{month}\NormalTok{(Date),}
                              \AttributeTok{Year=}\FunctionTok{year}\NormalTok{(Date)) }\SpecialCharTok{\%\textgreater{}\%}
                       \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Date\_combined =} \FunctionTok{my}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(Month,}\StringTok{"{-}"}\NormalTok{,Year)))}\SpecialCharTok{\%\textgreater{}\%} 
                       \FunctionTok{group\_by}\NormalTok{(Date\_combined)}\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{                       dplyr}\SpecialCharTok{::}\FunctionTok{summarise}\NormalTok{(}\AttributeTok{Mean.monthly.Ozone =} \FunctionTok{mean}\NormalTok{(Daily.Max}\FloatTok{.8}\NormalTok{hr.Ozone.Conc.Clean))}
\CommentTok{\#I used paste0 to combined Month and Year into a new column called Date\_combined}
\CommentTok{\#I used group\_by to summarize mean montly ozone concentrations}
\CommentTok{\#Separate pipe to create new Date column using lubridate package function: make\_date()}
\NormalTok{GaringerOzone.monthly}\OtherTok{\textless{}{-}}\NormalTok{GaringerOzone.monthly }\SpecialCharTok{\%\textgreater{}\%}
                       \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Date=}\FunctionTok{as.Date}\NormalTok{(Date\_combined))}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{9}
\tightlist
\item
  Generate two time series objects. Name the first
  \texttt{GaringerOzone.daily.ts} and base it on the dataframe of daily
  observations. Name the second \texttt{GaringerOzone.monthly.ts} and
  base it on the monthly average ozone values. Be sure that each
  specifies the correct start and end dates and the frequency of the
  time series.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#10}
\CommentTok{\#checking first and last dates of the observations}
\FunctionTok{first}\NormalTok{(GaringerOzone\_cleaned}\SpecialCharTok{$}\NormalTok{Date) }\CommentTok{\#first date is in January 2010}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "2010-01-01"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{last}\NormalTok{(GaringerOzone\_cleaned}\SpecialCharTok{$}\NormalTok{Date) }\CommentTok{\#last date is in December 2019}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "2019-12-31"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#First time series object: daily observations }
\NormalTok{GaringerOzone.daily.ts}\OtherTok{\textless{}{-}}\FunctionTok{ts}\NormalTok{(GaringerOzone\_cleaned}\SpecialCharTok{$}\NormalTok{Daily.Max}\FloatTok{.8}\NormalTok{hr.Ozone.Conc.Clean,}
                        \AttributeTok{start=}\FunctionTok{c}\NormalTok{(}\DecValTok{2010}\NormalTok{,}\DecValTok{1}\NormalTok{),}
                        \AttributeTok{end=}\FunctionTok{c}\NormalTok{(}\DecValTok{2019}\NormalTok{,}\DecValTok{12}\NormalTok{),}
                        \AttributeTok{frequency=}\DecValTok{365}\NormalTok{)}
\CommentTok{\#Second time series object: monthly average ozone values}
\NormalTok{GaringerOzone.monthly.ts}\OtherTok{\textless{}{-}} \FunctionTok{ts}\NormalTok{(GaringerOzone.monthly}\SpecialCharTok{$}\NormalTok{Mean.monthly.Ozone,}
                              \AttributeTok{start=}\FunctionTok{c}\NormalTok{(}\DecValTok{2010}\NormalTok{,}\DecValTok{1}\NormalTok{),}
                              \AttributeTok{end=}\FunctionTok{c}\NormalTok{(}\DecValTok{2019}\NormalTok{,}\DecValTok{12}\NormalTok{),}
                              \AttributeTok{frequency=}\DecValTok{12}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{10}
\tightlist
\item
  Decompose the daily and the monthly time series objects and plot the
  components using the \texttt{plot()} function.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#11}
\CommentTok{\#Decompose the time series objects }
\CommentTok{\#I used period for s.window, because I see a seasonal component from the lineplot in \#7}
\CommentTok{\#Daily}
\NormalTok{GaringerOzone.daily.decomposed}\OtherTok{\textless{}{-}}\FunctionTok{stl}\NormalTok{(GaringerOzone.daily.ts, }\AttributeTok{s.window=}\StringTok{"periodic"}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(GaringerOzone.daily.decomposed)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A07_TimeSeries_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Monthly }
\NormalTok{GaringerOzone.monthly.decomposed}\OtherTok{\textless{}{-}}\FunctionTok{stl}\NormalTok{(GaringerOzone.monthly.ts, }\AttributeTok{s.window=}\StringTok{"periodic"}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(GaringerOzone.monthly.decomposed)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A07_TimeSeries_files/figure-latex/unnamed-chunk-7-2.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{11}
\tightlist
\item
  Run a monotonic trend analysis for the monthly Ozone series. In this
  case the seasonal Mann-Kendall is most appropriate; why is this?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#12 Monotonic trend analysis for monthly Ozone series}
\NormalTok{trend.monthly.Ozone}\OtherTok{\textless{}{-}}\NormalTok{ Kendall}\SpecialCharTok{::}\FunctionTok{SeasonalMannKendall}\NormalTok{(GaringerOzone.monthly.ts)}
\NormalTok{trend.monthly.Ozone}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## tau = -0.143, 2-sided pvalue =0.046724
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(trend.monthly.Ozone)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Score =  -77 , Var(Score) = 1499
## denominator =  539.4972
## tau = -0.143, 2-sided pvalue =0.046724
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#I also ran the smk test to look at differences in each season}
\NormalTok{trend.monthly.Ozone.smk }\OtherTok{\textless{}{-}}\NormalTok{ trend}\SpecialCharTok{::}\FunctionTok{smk.test}\NormalTok{(GaringerOzone.monthly.ts)}
\FunctionTok{summary}\NormalTok{(trend.monthly.Ozone.smk)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Seasonal Mann-Kendall trend test (Hirsch-Slack test)
## 
## data: GaringerOzone.monthly.ts
## alternative hypothesis: two.sided
## 
## Statistics for individual seasons
## 
## H0
##                      S varS    tau      z Pr(>|z|)  
## Season 1:   S = 0   15  125  0.333  1.252  0.21050  
## Season 2:   S = 0   -1  125 -0.022  0.000  1.00000  
## Season 3:   S = 0   -4  124 -0.090 -0.269  0.78762  
## Season 4:   S = 0  -17  125 -0.378 -1.431  0.15241  
## Season 5:   S = 0  -15  125 -0.333 -1.252  0.21050  
## Season 6:   S = 0  -17  125 -0.378 -1.431  0.15241  
## Season 7:   S = 0  -11  125 -0.244 -0.894  0.37109  
## Season 8:   S = 0   -7  125 -0.156 -0.537  0.59151  
## Season 9:   S = 0   -5  125 -0.111 -0.358  0.72051  
## Season 10:   S = 0 -13  125 -0.289 -1.073  0.28313  
## Season 11:   S = 0 -13  125 -0.289 -1.073  0.28313  
## Season 12:   S = 0  11  125  0.244  0.894  0.37109  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{quote}
Answer: The seasonal Mann-Kendall is the most appropriate because I see
with the daily and monthly ozone data that there is seasonality in the
data. When I plotted the decomposed daily and monthly time series
objects I see that in the seasonal vs.~time graph that there is a strong
seasonal component. So, when running the Mann-Kendall we need to take
into consideration seasonality.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{12}
\tightlist
\item
  Create a plot depicting mean monthly ozone concentrations over time,
  with both a geom\_point and a geom\_line layer. Edit your axis labels
  accordingly.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 13}
\NormalTok{GaringerOzone.mean.monthly.plot}\OtherTok{\textless{}{-}}\FunctionTok{ggplot}\NormalTok{(GaringerOzone.monthly, }
                                        \FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Date,}\AttributeTok{y=}\NormalTok{Mean.monthly.Ozone))}\SpecialCharTok{+}
                                 \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha=}\DecValTok{1}\NormalTok{,}\AttributeTok{size=}\FloatTok{1.5}\NormalTok{)}\SpecialCharTok{+}
                                 \FunctionTok{geom\_line}\NormalTok{()}\SpecialCharTok{+}
                                 \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method=}\NormalTok{lm, }\AttributeTok{se=}\ConstantTok{FALSE}\NormalTok{)}\SpecialCharTok{+}
                                 \FunctionTok{labs}\NormalTok{(}\AttributeTok{y=}\StringTok{"Mean Monthly Ozone Concentration (ppm)"}\NormalTok{, }\AttributeTok{x=}\StringTok{"Date"}\NormalTok{,}
                                 \AttributeTok{title=}
          \StringTok{"Mean Monthly Ozone Concentrations from 2010 to 2019 at Garinger High School in North Carolina"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{scale\_x\_date}\NormalTok{(}\AttributeTok{date\_breaks =} \StringTok{"6 months"}\NormalTok{,}\AttributeTok{date\_labels =} \StringTok{"\%b \%Y"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{90}\NormalTok{, }\AttributeTok{hjust=}\DecValTok{1}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(GaringerOzone.mean.monthly.plot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{A07_TimeSeries_files/figure-latex/unnamed-chunk-9-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#I used theme(axis.text.x=element\_text(angle=90, hjust=1)) to rotate the x axis labels}
\CommentTok{\#scale\_x\_date(date\_breaks = "6 months",date\_labels = "\%b \%Y") used to rename time intervals}
\CommentTok{\#I added the geom\_smooth to better visualize the monotonic downward trend. }
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{13}
\tightlist
\item
  To accompany your graph, summarize your results in context of the
  research question. Include output from the statistical test in
  parentheses at the end of your sentence. Feel free to use multiple
  sentences in your interpretation.
\end{enumerate}

\begin{quote}
Answer: The ozone concentrations have a seasonal component at the
Garinger High School Station in North Carolina. As seen in the figure
above, the monthly mean ozone concentrations (ppm) peak during the
summmer months and dip in the winter months. From the Seasonal
Mann-Kendall test, with a p-value =0.046 \textless{} 0.05 alpha level,
we reject the null hypothesis that the overall mean monthly ozone
concentrations are stationary at Garinger High School Station in NC from
2010 to 2019 (tau = -0.143, p-value =0.046724). We can conclude that
there is a monotonic trend where mean monthly ozone concentrations are
slightly decreasing from 2010 to 2019. From the smk test, we see that
between each season the decreases is not significant
(p-value\textgreater0.05); however, the overall downward trend shows
that ozone concentrations have changed across the 2010s at Garinger
Station (Score=-77, tau = -0.143, p-value =0.046724).This downward trend
is also shown in the blue linear trendline on the graph above.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{14}
\item
  Subtract the seasonal component from the
  \texttt{GaringerOzone.monthly.ts}. Hint: Look at how we extracted the
  series components for the EnoDischarge on the lesson Rmd file.
\item
  Run the Mann Kendall test on the non-seasonal Ozone monthly series.
  Compare the results with the ones obtained with the Seasonal Mann
  Kendall on the complete series.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#15 Subtract seasonal component form GaringerOzone.monthly.ts}
\CommentTok{\#I turned the monthly decomposed object into a dataframe}
\NormalTok{GaringerOzone.monthly.components}\OtherTok{\textless{}{-}}\FunctionTok{as.data.frame}\NormalTok{(GaringerOzone.monthly.decomposed}\SpecialCharTok{$}\NormalTok{time.series[,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{]) }
\CommentTok{\# I used [,1:3] to get the seasonal, trend, and remainder columns}
\CommentTok{\#Now I need to subtract the seasonal column (from the GaringerOzone.monthly.components) }
\CommentTok{\#in order to look at the monthly.ts without seasonality}
\NormalTok{GaringerOzone.month.no.season.ts}\OtherTok{\textless{}{-}}\NormalTok{(GaringerOzone.monthly.ts}\SpecialCharTok{{-}}\NormalTok{GaringerOzone.monthly.components}\SpecialCharTok{$}\NormalTok{seasonal)}

\CommentTok{\#16 Mann Kendall test on non{-}seasonal Ozone monthly series}
\NormalTok{non.seasonal.Ozone.monthly.trend}\OtherTok{\textless{}{-}}\NormalTok{Kendall}\SpecialCharTok{::}\FunctionTok{MannKendall}\NormalTok{(GaringerOzone.month.no.season.ts)}
\NormalTok{non.seasonal.Ozone.monthly.trend}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## tau = -0.165, 2-sided pvalue =0.0075402
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(non.seasonal.Ozone.monthly.trend)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Score =  -1179 , Var(Score) = 194365.7
## denominator =  7139.5
## tau = -0.165, 2-sided pvalue =0.0075402
\end{verbatim}

\begin{quote}
Answer: Similar to the Seasonal Mann-Kendall test, the non-seasonal Mann
Kendall also found that the mean monthly ozone concentrations at
Garinger Station in North Carolina changes from 2010 to 2019. We reject
the null hypothesis that the mean monthly ozone concentrations are
stationary and conclude that there is a downward trend in mean monthly
ozone concentrations from 2010 to 2019 (tau=-0.165,
p-value=0.0075\textless{} 0.05-alpha level). The Mann Kendall p-value is
smaller than the seasonal mann-kendall p-value. When seasonal component
is taken out the Score is -1179 which is more negative than the Score
from the Seasonal Mann Kendall test which had a score of -77.The Mann
Kendall non-seasonal Score has a higher variance (V(Score)=194365) than
the seasonal Mann Kendall score (Var(Score)=1499).
\end{quote}

\end{document}
